/* config.js — generated by the build. Public settings only: the Supabase anon key is designed to be public. */
window.APP_CONFIG = {
  "slug": "spaced-repetition-cards",
  "name": "FlashForge",
  "supabaseUrl": "",
  "supabaseAnonKey": "",
  "aiProxy": "",
  "google": false,
  "prompts": [
    {
      "say": "Make 15 cards on the causes of World War I",
      "does": "Writes the cards into a new deck."
    },
    {
      "say": "Make my Spanish deck harder",
      "does": "Rewrites that deck's cards with tougher prompts."
    },
    {
      "say": "Start reviewing whatever is due",
      "does": "Opens a study session with today's due cards."
    }
  ]
};
